@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SETAParser" as SETAParser ADDRESSBOOKPARSER_COLOR
participant ":AddQCommandParser" as AddQCommandParser ADDQCOMMANDPARSER_COLOR
participant "a: AddQCommand" as AddQCommand ADDQCOMMAND_COLOR
box end

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":SETA" as SETA ADDRESSBOOK_COLOR

[-> LogicManager : execute("addq Why?")
activate LogicManager

LogicManager -> SETAParser : parseCommand("addq Why?")
activate SETAParser

SETAParser -> AddQCommandParser : parse(" Why?")
activate AddQCommandParser

Create AddQCommand
AddQCommandParser -> AddQCommand : parse(" Why")
activate AddQCommand

AddQCommand --> AddQCommandParser : a
deactivate AddQCommand

AddQCommandParser --> SETAParser : a
deactivate AddQCommandParser

SETAParser --> LogicManager : a
deactivate SETAParser

LogicManager -> AddQCommand : execute(model)
activate AddQCommand

AddQCommand -> Model : addQuestion(toAdd)
activate Model

Model -> SETA : addQuestion(toAdd)
activate SETA

SETA -> SETA : resetData(ReadOnlySETA newData)
SETA --> Model
deactivate SETA


Model --> AddQCommand
deactivate Model

AddQCommand --> LogicManager : commandResult
deactivate AddQCommand
destroy AddQCommand


[<--LogicManager : commandResult
deactivate LogicManager
@enduml
