@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SETAParser" as SETAParser LOGIC_COLOR
participant ":AddStuCommandParser" as AddStuCommandParser LOGIC_COLOR
participant "a:AddStuCommand" as AddStuCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":SETA" as SETA MODEL_COLOR
end box
[-> LogicManager : execute(addstu n/John h/@johnlim e/john@gmail.com)
activate LogicManager

LogicManager -> SETAParser : parseCommand(addstu n/John h/@johnlim e/john@gmail.com)
activate SETAParser

create AddStuCommandParser
SETAParser -> AddStuCommandParser
activate AddStuCommandParser

AddStuCommandParser --> SETAParser
deactivate AddStuCommandParser

SETAParser -> AddStuCommandParser : parse("n/John h/@johnlim e/john@gmail.com")
activate AddStuCommandParser

create AddStuCommand
AddStuCommandParser -> AddStuCommand
activate AddStuCommand

AddStuCommand --> AddStuCommandParser
deactivate AddStuCommand

SETAParser --> LogicManager : a
deactivate SETAParser

LogicManager -> AddStuCommand : execute()
activate AddStuCommand

AddStuCommand -> Model : addStudent(Student student)
activate Model

Model -> SETA : addStudent(Student s)
activate SETA

SETA -> SETA :resetData(ReadOnlySETA newData)
SETA --> Model :
deactivate SETA

Model --> AddStuCommand
deactivate Model

AddStuCommand --> LogicManager : result
deactivate AddStuCommand
AddStuCommand -[hidden]-> LogicManager : result
destroy AddStuCommand

[<--LogicManager
deactivate LogicManager
@enduml
