@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SETAParser" as SETAParser LOGIC_COLOR
participant ":AttendanceCommandParser" as AttendanceCommandParser LOGIC_COLOR
participant "a:AttendanceCommand" as AttendanceCommand LOGIC_COLOR
end box

[-> LogicManager : execute("attendance 1")
activate LogicManager

LogicManager -> SETAParser : parseCommand("attendance 1")
activate SETAParser

create AttendanceCommandParser
SETAParser -> AttendanceCommandParser
activate AttendanceCommandParser

AttendanceCommandParser --> SETAParser
deactivate AttendanceCommandParser

SETAParser -> AttendanceCommandParser : parse("1")
activate AttendanceCommandParser

create AttendanceCommand
AttendanceCommandParser -> AttendanceCommand
activate AttendanceCommand

AttendanceCommand --> AttendanceCommandParser : a
deactivate AttendanceCommand

AttendanceCommandParser --> SETAParser : a
deactivate AttendanceCommandParser

AttendanceCommandParser -[hidden]-> SETAParser
destroy AttendanceCommandParser

SETAParser --> LogicManager : a
deactivate SETAParser

ref over LogicManager : execute attendance command

[<--LogicManager
deactivate LogicManager
@enduml
